version: '3.3' 

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'flightstore'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'flightuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'takeoff'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'captain'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '4406:3306'
    expose:
      # Opens port 3306 on the container
      - '4406'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  
  app:
    build: ../flightstore-airplane
    image: ualter/flightstore-airplane
    environment:
      - MYSQL_IP=db
      - MYSQL_PORT=3306
    ports:
      - 9181:9180
    expose:
      - '9181'    
  
  #Alternative WebConsole for MySQL    
  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8383:8080
      
volumes:
  my-db:    