kind: Service
apiVersion: v1
metadata:
  labels:
    app: flightstore-airliner
    name: flightstore-airliner
  name: flightstore-airliner
  namespace: myproject
spec:
  selector:
    app: flightstore-airliner
    deploymentconfig: flightstore-airliner
  ports:
    - name: 9180-tcp
      port: 80
      protocol: TCP
      targetPort: 9180