kind: DeploymentConfig
apiVersion: "v1"
metadata:
  name: flightstore-airliner
  namespace: myproject
  labels:
    app: flightstore-airliner
    name: flightstore-airliner
spec:
  replicas: 1
  selector:
    app: flightstore-airliner
    deploymentconfig: flightstore-airliner
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling  
  template: 
    metadata:
      labels:
        app: flightstore-airliner
        deploymentconfig: flightstore-airliner
    spec:
      containers:
        - env:
            - name: JASYPT_ENCRYPTOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: encryptor-password
                  name: jasypt-encryptor
            - name: SPRING_PROFILES_ACTIVE
              value: minishift
          image: 'my-registry:5000/ualter-flightstore-airliner:latest'
          imagePullPolicy: Always
          name: ualter-flightstore-airliner
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: flightstore-airliner-volume-1
      imagePullSecrets:
        - name: my-registry-secret
      restartPolicy: Always
      volumes:
        - emptyDir: {}
          name: flightstore-airliner-volume-1
  triggers:
    - type: "ConfigChange"
    
  
