version: '3.3'

services:
    registry:
        image: registry:2
        restart: always
        ports:
          - "5000"
        environment:
          REGISTRY_STORAGE_DELETE_ENABLED: 'true'
          REGISTRY_HTTP_ADDR: 0.0.0.0:5000
          REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
          REGISTRY_HTTP_TLS_KEY: /certs/domain.key
          #REGISTRY_STORAGE: s3
          #REGISTRY_STORAGE_S3_ACCESSKEY: <api access key>
          #REGISTRY_STORAGE_S3_SECRETKEY: <api secret>
          #REGISTRY_STORAGE_S3_BUCKET: <bucket name>
          #REGISTRY_STORAGE_S3_REGION: <region>
          #REGISTRY_HEALTH_STORAGEDRIVER_ENABLED: false
        ports:
          - "5000:5000"
        volumes:
          - ${MY_REGISTRY_CERTS}:/certs    
    registry-frontend:
        image: konradkleine/docker-registry-frontend:v2
        restart: always
        environment:
          ENV_DOCKER_REGISTRY_HOST: 'registry'
          ENV_DOCKER_REGISTRY_PORT: 5000
        links:
          - registry
        ports:
          - "8080:80"
        expose:
          - 80