version: '3.3' 

services:
  app:
    build: .
    image: ualter/flightstore-airplane
    depends_on:
      - db
    environment:
      - MYSQL_IP=db 
      - MYSQL_PORT=3306
      - spring.flyway.user=root
      - spring.flyway.password=${MYSQL_ROOT_PASSWORD}
      - jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}
      - spring.flyway.placeholders.userpass=${MYSQL_PASSWORD}
      - spring.flyway.connect-retries=30
    ports:
      - 9181:9180
    expose:
      - '9181'
      
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=flightstore
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '4406:3306'
    expose:
      - '4406'
    volumes:
      - my-db:/var/lib/mysql
      
      
  
  #Alternative WebConsole for MySQL    
  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8383:8080
      
volumes:
  my-db:    