kind: DeploymentConfig
apiVersion: "v1"
metadata:
  name: flightstore-airplane
  namespace: myproject
  labels:
    app: flightstore-airplane
    name: flightstore-airplane
spec:
  replicas: 1
  selector:
    app: flightstore-airplane
    deploymentconfig: flightstore-airplane
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling  
  template: 
    metadata:
      labels:
        app: flightstore-airplane
        deploymentconfig: flightstore-airplane
    spec:
      containers:
        - env:
            - name: JASYPT_ENCRYPTOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: encryptor-password
                  name: jasypt-encryptor
            - name: SPRING_PROFILES_ACTIVE
              value: minishift
          image: 'my-registry:5000/ualter-flightstore-airplane:latest'
          imagePullPolicy: Always
          name: ualter-flightstore-airplane
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: flightstore-airplane-volume-1
          #  - mountPath: /etc/config
          #    name: configmap-flightstore-airplane   
      imagePullSecrets:
        - name: my-registry-secret
      restartPolicy: Always
      volumes:
        - emptyDir: {}
          name: flightstore-airplane-volume-1
        #- name: configmap-flightstore-airplane
        #  configMap:
        #    name: flightstore-airplane        
  triggers:
    - type: "ConfigChange"
    
  
