version: '3.3' 

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=flightstore
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '4406:3306'
    expose:
      # Opens port 3306 on the container
      - '4406'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  
  #Alternative WebConsole for MySQL    
  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8383:8080
      
volumes:
  my-db:    